apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
        - name: transaction
          image: dragonevo/ewallet-transaction:latest
          ports:
            - containerPort: 8082 # HTTP
          env:
            - name: UMS_GRPC_HOST
              value: ums:7000
            - name: NOTIFICATION_GRPC_HOST
              value: notification:7003
