apiVersion: apps/v1
kind: Deployment
metadata:
  name: ums
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ums
  template:
    metadata:
      labels:
        app: ums
    spec:
      containers:
        - name: ums
          image: dragonevo/ewallet-ums:latest
          ports:
            - containerPort: 8080 # HTTP
            - containerPort: 7000 # gRPC
          env:
            - name: NOTIFICATION_GRPC_HOST
              value: notification:7003
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
